# cloudbuild.yaml
substitutions:
  _REGION: "europe-west1"
  _REPO: "eire-scraping-repo" # Artifact Registry repo name
  _IMAGE_NAME: "eire-scraper" # image name inside that repo
  _JOB_COMPLETION: "eire-scrap-completion"
  _JOB_NCBO: "eire-scrap-ncbo"
  _JOB_RAW: "eire-scrap-raw"
  _ENTRYPOINT_SCRIPT: "/app/main.py"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build the container image
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "."

  # 2. Push the container image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"

  # 3. Deploy the job for 'completion'
  # Now calls the single entrypoint script with the correct --job argument.
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Job - completion"
    entrypoint: gcloud
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "${_JOB_COMPLETION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--command"
      - "python"
      - "--args"
      - "${_ENTRYPOINT_SCRIPT},--job,scrap_completion" # Pass script name and arguments
      - "--cpu"
      - "2"
      - "--memory"
      - "1Gi"
      - "--max-retries"
      - "0"

  # 4. Deploy the job for 'ncbo'
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Job - ncbo"
    entrypoint: gcloud
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "${_JOB_NCBO}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--command"
      - "python"
      - "--args"
      - "${_ENTRYPOINT_SCRIPT},--job,scrap_ncbo" # Pass script name and arguments
      - "--cpu"
      - "2"
      - "--memory"
      - "1Gi"
      - "--max-retries"
      - "0"

  # 5. Deploy the job for 'raw'
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Job - raw"
    entrypoint: gcloud
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "${_JOB_RAW}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--command"
      - "python"
      - "--args"
      - "${_ENTRYPOINT_SCRIPT},--job,scrap_raw_applications" # Pass script name and arguments
      - "--cpu"
      - "2"
      - "--memory"
      - "1Gi"
      - "--max-retries"
      - "0"

# This section lists the container images that are built by this pipeline.
# Cloud Build will push these images to the registry specified in the 'Push' step.
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
