# cloudbuild.yaml
substitutions:
  _REGION: "europe-west1"
  _REPO: "eire-scraping-repo"
  _IMAGE_NAME: "eire-scraper"
  _JOB_COMPLETION: "eire-scrap-completion"
  _JOB_NCBO: "eire-scrap-ncbo"
  _JOB_RAW: "eire-scrap-raw"

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}",
        ".",
      ]

  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}",
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Job - completion
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
        if ! gcloud run jobs describe "${_JOB_COMPLETION}" --region "${_REGION}" >/dev/null 2>&1; then
          gcloud run jobs create "${_JOB_COMPLETION}" \
            --region "${_REGION}" \
            --image "$IMAGE" \
            --command "python" \
            --args "/app/scrap_completion.py" \
            --cpu 1 --memory 512Mi --max-retries 0
        fi
        gcloud run jobs update "${_JOB_COMPLETION}" \
          --region "${_REGION}" \
          --image "$IMAGE" \
          --command "python" \
          --args "/app/scrap_completion.py"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Job - ncbo
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
        if ! gcloud run jobs describe "${_JOB_NCBO}" --region "${_REGION}" >/dev/null 2>&1; then
          gcloud run jobs create "${_JOB_NCBO}" \
            --region "${_REGION}" \
            --image "$IMAGE" \
            --command "python" \
            --args "/app/scrap_ncbo.py" \
            --cpu 1 --memory 512Mi --max-retries 0
        fi
        gcloud run jobs update "${_JOB_NCBO}" \
          --region "${_REGION}" \
          --image "$IMAGE" \
          --command "python" \
          --args "/app/scrap_ncbo.py"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Job - raw
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
        if ! gcloud run jobs describe "${_JOB_RAW}" --region "${_REGION}" >/dev/null 2>&1; then
          gcloud run jobs create "${_JOB_RAW}" \
            --region "${_REGION}" \
            --image "$IMAGE" \
            --command "python" \
            --args "/app/scrap_raw_applications.py" \
            --cpu 1 --memory 512Mi --max-retries 0
        fi
        gcloud run jobs update "${_JOB_RAW}" \
          --region "${_REGION}" \
          --image "$IMAGE" \
          --command "python" \
          --args "/app/scrap_raw_applications.py"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"
